services:
  - type: web
    name: covid19-dashboard
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run app.py"
    envVars:
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
